
/*
 * This file was generated by the SOM Compiler.
 * FileName: idl\textfldr.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * 
 *    Module Name: TEXTFLDR
 * 
 *    OS/2 Work Place Shell Sample Program
 * 
 *    Copyright (C) 1993 IBM Corporation
 * 
 *        DISCLAIMER OF WARRANTIES.  The following [enclosed] code is
 *        sample code created by IBM Corporation. This sample code is not
 *        part of any standard or IBM product and is provided to you solely
 *        for  the purpose of assisting you in the development of your
 *        applications.  The code is provided "AS IS", without
 *        warranty of any kind.  IBM shall not be liable for any damages
 *        arising out of your use of the sample code, even if they have been
 *        advised of the possibility of such damages.
 * 
 */


#ifndef SOM_TextFolder_h
#define SOM_TextFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef TextFolder
#define TextFolder SOMObject
#endif
/*
 *  CLASS: TextFolder
 * 
 *  CLASS HIERARCHY:
 * 
 *      SOMObject
 *        ÀÄÄ WPObject
 *              ÀÄÄ WPFileSystem
 *                    ÀÄÄ WPFolder
 *                          ÀÄÄ  TextFolder
 * 
 *  DESCRIPTION:
 * 
 *     This is the TextFolder object class. This object is similar to
 *     normal folders. The text folder rejects any object that isn't
 *     a file system object that only contains text. The TextFolder accepts
 *     file system objects that have a type of 'Plain Text' or have no type
 *     and contain text characters only.
 * 
 *     An instance of this class can be created as a Workplace object.
 * 
 */
#include <wpfolder.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_TextFolder
    #define M_TextFolder SOMObject
#endif /* M_TextFolder */

/*
 * End of bindings for IDL types.
 */

/*
 * Passthru lines: File: "C.h", "after"
 */



#define TextFolder_MajorVersion 1
#define TextFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define TextFolderNewClass TextFolderwpsc
#pragma linkage(TextFolderwpsc, system)
#define TextFolderClassData TextFolderwpsd
#define TextFolderCClassData TextFolderwpsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define TextFolder_classObj TextFolderClassData.classObject
#define _TextFolder TextFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK TextFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(TextFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct TextFolderClassDataStructure {
	SOMClass *classObject;
	somMToken IsTextFile;
	somMToken ValidateDragAndDrop;
} SOMDLINK TextFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct TextFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK TextFolderCClassData;

/*
 * New and Renew macros for TextFolder
 */
#define TextFolderNew() \
   ( _TextFolder ? \
	_somNew(_TextFolder) \
	: ( TextFolderNewClass(\
		TextFolder_MajorVersion, \
		TextFolder_MinorVersion),\
	   _somNew(_TextFolder)))
#define TextFolderRenew(buf) \
   ( _TextFolder ? \
	_somRenew(_TextFolder, buf) \
	: ( TextFolderNewClass(\
		TextFolder_MajorVersion, \
		TextFolder_MinorVersion),\
	   _somRenew(_TextFolder, buf)))

/*
 * Override method: wpFilterPopupMenu
 */
#define TextFolder_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpAddFolderView2Page
 */
#define TextFolder_wpAddFolderView2Page(somSelf,hwndNotebook) \
	WPFolder_wpAddFolderView2Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddFolderIncludePage
 */
#define TextFolder_wpAddFolderIncludePage(somSelf,hwndNotebook) \
	WPFolder_wpAddFolderIncludePage(somSelf,hwndNotebook)

/*
 * Override method: wpDragOver
 */
#define TextFolder_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpDrop
 */
#define TextFolder_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define TextFolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define TextFolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define TextFolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define TextFolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define TextFolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define TextFolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define TextFolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define TextFolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define TextFolder_wpPopulate WPFolder_wpPopulate
#define TextFolder_wpQueryContent WPFolder_wpQueryContent
#define TextFolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define TextFolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define TextFolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define TextFolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define TextFolder_wpAddFolderMenu2Page WPFolder_wpAddFolderMenu2Page
#define TextFolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define TextFolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define TextFolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define TextFolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define TextFolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define TextFolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define TextFolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define TextFolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define TextFolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define TextFolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define TextFolder_wpDeleteContents WPFolder_wpDeleteContents
#define TextFolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define TextFolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define TextFolder_wpSearchFolder WPFolder_wpSearchFolder
#define TextFolder_wpContainsFolders WPFolder_wpContainsFolders
#define TextFolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define TextFolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define TextFolder_wpAddToContent WPFolder_wpAddToContent
#define TextFolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define TextFolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define TextFolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define TextFolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define TextFolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define TextFolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define TextFolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define TextFolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define TextFolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define TextFolder_wpFlushNotifications WPFolder_wpFlushNotifications
#define TextFolder_wpSetMenuBarVisibility WPFolder_wpSetMenuBarVisibility
#define TextFolder_wpQueryMenuBarVisibility WPFolder_wpQueryMenuBarVisibility
#define TextFolder_wpQueryIconTextBackgroundColor WPFolder_wpQueryIconTextBackgroundColor
#define TextFolder_wpSetIconTextBackgroundColor WPFolder_wpSetIconTextBackgroundColor
#define TextFolder_wpQueryIconTextColor WPFolder_wpQueryIconTextColor
#define TextFolder_wpSetIconTextColor WPFolder_wpSetIconTextColor
#define TextFolder_wpQueryShadowTextColor WPFolder_wpQueryShadowTextColor
#define TextFolder_wpSetShadowTextColor WPFolder_wpSetShadowTextColor
#define TextFolder_wpQueryIconTextVisibility WPFolder_wpQueryIconTextVisibility
#define TextFolder_wpSetIconTextVisibility WPFolder_wpSetIconTextVisibility
#define TextFolder_wpQueryFldrBackground WPFolder_wpQueryFldrBackground
#define TextFolder_wpSetFldrBackground WPFolder_wpSetFldrBackground
#define TextFolder_wpInitData WPObject_wpInitData
#define TextFolder_wpUnInitData WPObject_wpUnInitData
#define TextFolder_wpFree WPObject_wpFree
#define TextFolder_wpDelete WPObject_wpDelete
#define TextFolder_wpConfirmDelete WPObject_wpConfirmDelete
#define TextFolder_wpSaveState WPObject_wpSaveState
#define TextFolder_wpRestoreState WPObject_wpRestoreState
#define TextFolder_wpMenuItemSelected WPObject_wpMenuItemSelected
#define TextFolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define TextFolder_wpOpen WPObject_wpOpen
#define TextFolder_wpSetup WPObject_wpSetup
#define TextFolder_wpMoveObject WPObject_wpMoveObject
#define TextFolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define TextFolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define TextFolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define TextFolder_wpFormatDragItem WPObject_wpFormatDragItem
#define TextFolder_wpRender WPObject_wpRender
#define TextFolder_wpRefresh WPFileSystem_wpRefresh
#define TextFolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define TextFolder_wpRenderComplete WPObject_wpRenderComplete
#define TextFolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define TextFolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define TextFolder_wpObjectReady WPObject_wpObjectReady
#define TextFolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define TextFolder_wpModifyMenu WPObject_wpModifyMenu
#define TextFolder_wpFilterMenu WPObject_wpFilterMenu
#define TextFolder_wpDisplayMenu WPObject_wpDisplayMenu
#define TextFolder_somDefaultInit SOMObject_somDefaultInit
#define TextFolder_somDestruct SOMObject_somDestruct
#define TextFolder_wpSetIconData WPObject_wpSetIconData
#define TextFolder_wpSetRealName WPFileSystem_wpSetRealName
#define TextFolder_wpSetType WPFileSystem_wpSetType
#define TextFolder_wpQueryType WPFileSystem_wpQueryType
#define TextFolder_wpSetAttr WPFileSystem_wpSetAttr
#define TextFolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define TextFolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define TextFolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define TextFolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define TextFolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define TextFolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define TextFolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define TextFolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define TextFolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define TextFolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define TextFolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define TextFolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define TextFolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define TextFolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define TextFolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define TextFolder_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define TextFolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define TextFolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define TextFolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define TextFolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define TextFolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define TextFolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define TextFolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define TextFolder_wpQueryFileSizeL WPFileSystem_wpQueryFileSizeL
#define TextFolder_wpSetFileSizeL WPFileSystem_wpSetFileSizeL
#define TextFolder_wpQueryHandle WPObject_wpQueryHandle
#define TextFolder_wpSaveImmediate WPObject_wpSaveImmediate
#define TextFolder_wpSetTitle WPObject_wpSetTitle
#define TextFolder_wpViewObject WPObject_wpViewObject
#define TextFolder_wpSwitchTo WPObject_wpSwitchTo
#define TextFolder_wpCopyObject WPObject_wpCopyObject
#define TextFolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define TextFolder_wpQueryIcon WPObject_wpQueryIcon
#define TextFolder_wpQueryIconData WPObject_wpQueryIconData
#define TextFolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define TextFolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define TextFolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define TextFolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define TextFolder_wpAppendObject WPObject_wpAppendObject
#define TextFolder_wpReplaceObject WPObject_wpReplaceObject
#define TextFolder_wpQueryStyle WPObject_wpQueryStyle
#define TextFolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define TextFolder_wpIdentify WPObject_wpIdentify
#define TextFolder_wpIsDeleteable WPObject_wpIsDeleteable
#define TextFolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define TextFolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define TextFolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define TextFolder_wpAllocMem WPObject_wpAllocMem
#define TextFolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define TextFolder_wpClose WPObject_wpClose
#define TextFolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define TextFolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define TextFolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define TextFolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define TextFolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define TextFolder_wpCreateAnother WPObject_wpCreateAnother
#define TextFolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define TextFolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define TextFolder_wpDisplayHelp WPObject_wpDisplayHelp
#define TextFolder_wpEndConversation WPObject_wpEndConversation
#define TextFolder_wpFindUseItem WPObject_wpFindUseItem
#define TextFolder_wpFreeMem WPObject_wpFreeMem
#define TextFolder_wpHide WPObject_wpHide
#define TextFolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define TextFolder_wpInsertMenuItems WPObject_wpInsertMenuItems
#define TextFolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define TextFolder_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define TextFolder_wpPrintObject WPObject_wpPrintObject
#define TextFolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define TextFolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define TextFolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define TextFolder_wpQueryError WPObject_wpQueryError
#define TextFolder_wpSetFolder WPObject_wpSetFolder
#define TextFolder_wpQueryFolder WPObject_wpQueryFolder
#define TextFolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define TextFolder_wpSetTaskRec WPObject_wpSetTaskRec
#define TextFolder_wpFindTaskRec WPObject_wpFindTaskRec
#define TextFolder_wpQueryTitle WPObject_wpQueryTitle
#define TextFolder_wpRegisterView WPObject_wpRegisterView
#define TextFolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define TextFolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define TextFolder_wpRestore WPObject_wpRestore
#define TextFolder_wpRestoreData WPObject_wpRestoreData
#define TextFolder_wpRestoreLong WPObject_wpRestoreLong
#define TextFolder_wpRestoreString WPObject_wpRestoreString
#define TextFolder_wpSaveData WPObject_wpSaveData
#define TextFolder_wpSaveDeferred WPObject_wpSaveDeferred
#define TextFolder_wpSaveLong WPObject_wpSaveLong
#define TextFolder_wpSaveString WPObject_wpSaveString
#define TextFolder_wpScanSetupString WPObject_wpScanSetupString
#define TextFolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define TextFolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define TextFolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define TextFolder_wpSetDefaultView WPObject_wpSetDefaultView
#define TextFolder_wpSetError WPObject_wpSetError
#define TextFolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define TextFolder_wpSetupOnce WPObject_wpSetupOnce
#define TextFolder_wpSetIcon WPObject_wpSetIcon
#define TextFolder_wpSetMinWindow WPObject_wpSetMinWindow
#define TextFolder_wpModifyStyle WPObject_wpModifyStyle
#define TextFolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define TextFolder_wpUnlockObject WPObject_wpUnlockObject
#define TextFolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define TextFolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define TextFolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define TextFolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define TextFolder_wpSetObjectID WPObject_wpSetObjectID
#define TextFolder_wpQueryObjectID WPObject_wpQueryObjectID
#define TextFolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define TextFolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define TextFolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define TextFolder_wpFindViewItem WPObject_wpFindViewItem
#define TextFolder_wpLockObject WPObject_wpLockObject
#define TextFolder_wpIsLocked WPObject_wpIsLocked
#define TextFolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define TextFolder_wpWaitForClose WPObject_wpWaitForClose
#define TextFolder_wpSetMenuStyle WPObject_wpSetMenuStyle
#define TextFolder_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define TextFolder_wpSetStyle WPObject_wpSetStyle
#define TextFolder_somInit SOMObject_somInit
#define TextFolder_somUninit SOMObject_somUninit
#define TextFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define TextFolder_somDefaultAssign SOMObject_somDefaultAssign
#define TextFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define TextFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define TextFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define TextFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define TextFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define TextFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define TextFolder_somFree SOMObject_somFree
#define TextFolder_somGetClass SOMObject_somGetClass
#define TextFolder_somGetClassName SOMObject_somGetClassName
#define TextFolder_somGetSize SOMObject_somGetSize
#define TextFolder_somIsA SOMObject_somIsA
#define TextFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define TextFolder_somRespondsTo SOMObject_somRespondsTo
#define TextFolder_somDispatch SOMObject_somDispatch
#define TextFolder_somClassDispatch SOMObject_somClassDispatch
#define TextFolder_somCastObj SOMObject_somCastObj
#define TextFolder_somResetObj SOMObject_somResetObj
#define TextFolder_somDispatchV SOMObject_somDispatchV
#define TextFolder_somDispatchL SOMObject_somDispatchL
#define TextFolder_somDispatchA SOMObject_somDispatchA
#define TextFolder_somDispatchD SOMObject_somDispatchD
#define TextFolder_somPrintSelf SOMObject_somPrintSelf
#define TextFolder_somDumpSelf SOMObject_somDumpSelf
#define TextFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_TextFolder_h */

#ifndef SOM_M_TextFolder_h
#define SOM_M_TextFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_TextFolder
#define M_TextFolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_TextFolder_MajorVersion 1
#define M_TextFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_TextFolderNewClass TextFolderwpsc
#pragma linkage(TextFolderwpsc, system)
#define M_TextFolderClassData TextFolderwpsd
#define M_TextFolderCClassData TextFolderwpsx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_TextFolder_classObj M_TextFolderClassData.classObject
#define _M_TextFolder M_TextFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_TextFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_TextFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_TextFolderClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_TextFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_TextFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_TextFolderCClassData;

/*
 * New and Renew macros for M_TextFolder
 */
#define M_TextFolderNew() \
   ( _M_TextFolder ? \
	_somNew(_M_TextFolder) \
	: ( M_TextFolderNewClass(\
		M_TextFolder_MajorVersion, \
		M_TextFolder_MinorVersion),\
	   _somNew(_M_TextFolder)))
#define M_TextFolderRenew(buf) \
   ( _M_TextFolder ? \
	_somRenew(_M_TextFolder, buf) \
	: ( M_TextFolderNewClass(\
		M_TextFolder_MajorVersion, \
		M_TextFolder_MinorVersion),\
	   _somRenew(_M_TextFolder, buf)))

/*
 * Override method: wpclsQueryTitle
 */
#define M_TextFolder_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_TextFolder_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_TextFolder_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_TextFolder_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_TextFolder_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_TextFolder_wpclsInitData M_WPObject_wpclsInitData
#define M_TextFolder_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_TextFolder_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_TextFolder_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_TextFolder_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_TextFolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_TextFolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_TextFolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_TextFolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_TextFolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_TextFolder_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_TextFolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_TextFolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_TextFolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_TextFolder_wpclsNew M_WPObject_wpclsNew
#define M_TextFolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_TextFolder_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_TextFolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_TextFolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_TextFolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_TextFolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_TextFolder_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_TextFolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_TextFolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_TextFolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_TextFolder_wpclsSetError M_WPObject_wpclsSetError
#define M_TextFolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_TextFolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_TextFolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_TextFolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_TextFolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_TextFolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_TextFolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_TextFolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_TextFolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_TextFolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_TextFolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_TextFolder_somUninit SOMObject_somUninit
#define M_TextFolder_somClassReady SOMClass_somClassReady
#define M_TextFolder_somNew SOMClass_somNew
#define M_TextFolder_somRenew SOMClass_somRenew
#define M_TextFolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_TextFolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_TextFolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_TextFolder_somNewNoInit SOMClass_somNewNoInit
#define M_TextFolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_TextFolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_TextFolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_TextFolder_somAllocate SOMClass_somAllocate
#define M_TextFolder_somDeallocate SOMClass_somDeallocate
#define M_TextFolder_somInitClass SOMClass_somInitClass
#define M_TextFolder_somInitMIClass SOMClass_somInitMIClass
#define M_TextFolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_TextFolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_TextFolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_TextFolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_TextFolder_somGetClassData SOMClass_somGetClassData
#define M_TextFolder_somSetClassData SOMClass_somSetClassData
#define M_TextFolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_TextFolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_TextFolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_TextFolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_TextFolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_TextFolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_TextFolder_somGetMethodData SOMClass_somGetMethodData
#define M_TextFolder_somGetRdStub SOMClass_somGetRdStub
#define M_TextFolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_TextFolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_TextFolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_TextFolder_somGetName SOMClass_somGetName
#define M_TextFolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_TextFolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_TextFolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_TextFolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_TextFolder_somGetParent SOMClass_somGetParent
#define M_TextFolder_somGetParents SOMClass_somGetParents
#define M_TextFolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_TextFolder_somFindMethod SOMClass_somFindMethod
#define M_TextFolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_TextFolder_somFindSMethod SOMClass_somFindSMethod
#define M_TextFolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_TextFolder_somLookupMethod SOMClass_somLookupMethod
#define M_TextFolder_somCheckVersion SOMClass_somCheckVersion
#define M_TextFolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_TextFolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_TextFolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_TextFolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_TextFolder_somDefaultInit SOMObject_somDefaultInit
#define M_TextFolder_somDestruct SOMObject_somDestruct
#define M_TextFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_TextFolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_TextFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_TextFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_TextFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_TextFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_TextFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_TextFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_TextFolder_somInit SOMObject_somInit
#define M_TextFolder_somFree SOMObject_somFree
#define M_TextFolder_somGetClass SOMObject_somGetClass
#define M_TextFolder_somGetClassName SOMObject_somGetClassName
#define M_TextFolder_somGetSize SOMObject_somGetSize
#define M_TextFolder_somIsA SOMObject_somIsA
#define M_TextFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_TextFolder_somRespondsTo SOMObject_somRespondsTo
#define M_TextFolder_somDispatch SOMObject_somDispatch
#define M_TextFolder_somClassDispatch SOMObject_somClassDispatch
#define M_TextFolder_somCastObj SOMObject_somCastObj
#define M_TextFolder_somResetObj SOMObject_somResetObj
#define M_TextFolder_somDispatchV SOMObject_somDispatchV
#define M_TextFolder_somDispatchL SOMObject_somDispatchL
#define M_TextFolder_somDispatchA SOMObject_somDispatchA
#define M_TextFolder_somDispatchD SOMObject_somDispatchD
#define M_TextFolder_somPrintSelf SOMObject_somPrintSelf
#define M_TextFolder_somDumpSelf SOMObject_somDumpSelf
#define M_TextFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_TextFolder_h */
